import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
})

test('search selects a timezone and only adds it after confirmation', async ({ page }, testInfo) => {
  await page.getByRole('combobox', { name: /search cities/i }).fill('Asia/Tokyo')
  await page.getByRole('option', { name: /Tokyo/i }).first().click()
  await expect(page.getByText('Asia / Tokyo').first()).toBeVisible()
  await expect(page.getByRole('article').filter({ hasText: 'Tokyo' })).toHaveCount(0)
  const addButton = page.getByRole('button', { name: 'Add to comparison' })
  await expect(addButton).toHaveCSS('background-color', 'rgb(229, 57, 53)')
  await expect(addButton).toHaveCSS('color', 'rgb(17, 17, 17)')
  await addButton.click()
  if ((await page.viewportSize())!.width <= 800) {
    await page.locator('svg.rsm-svg').click({ position: { x: 5, y: 5 } })
  }
  const tokyoCard = page.getByRole('article').filter({ hasText: 'Tokyo' })
  await expect(tokyoCard).toBeVisible()
  await expect(tokyoCard.locator('.card-country')).toHaveText('Japan')
  await expect(tokyoCard.locator('.card-abbreviation')).toHaveText('· JST')
  const londonCard = page.getByRole('article').filter({ hasText: 'London' })
  await expect(londonCard.locator('.card-time-icon')).toHaveCount(1)
  await expect(londonCard.locator('.card-time-icon')).toHaveAttribute('aria-label', /^(Working hours|Nighttime|Outside working hours)$/)
  await expect(tokyoCard.locator('.card-time-icon')).toHaveCount(1)
  await page.screenshot({ path: testInfo.outputPath('timezone-card-icons.png'), fullPage: true })
  const londonBounds = (await londonCard.boundingBox())!
  const tokyoBounds = (await tokyoCard.boundingBox())!
  await page.mouse.move(londonBounds.x + londonBounds.width / 2, londonBounds.y + londonBounds.height / 2)
  await page.mouse.down()
  await page.mouse.move(londonBounds.x + londonBounds.width / 2 + 10, londonBounds.y + londonBounds.height / 2, { steps: 2 })
  await page.mouse.move(tokyoBounds.x + tokyoBounds.width / 2, tokyoBounds.y + tokyoBounds.height / 2, { steps: 8 })
  await page.mouse.up()
  await expect(page.getByRole('article').first()).toContainText('Tokyo')
  await page.reload()
  await expect(page.locator('.timezone-card').filter({ hasText: 'Tokyo' })).toHaveCount(1)
})

test('GMT offset fallbacks are not displayed', async ({ page }) => {
  await page.getByRole('combobox', { name: /search cities/i }).fill('Pacific/Fiji')
  await page.getByRole('option', { name: /Fiji/i }).first().click()

  const sidebar = page.getByRole('complementary', { name: 'Selected timezone details' })
  await expect(sidebar.locator('.zone-meta').first()).toHaveText(/^UTC\+12 now$/)
  await expect(sidebar.getByText(/GMT(?:[+-]\d+)?/i)).toHaveCount(0)
})

test('map countries and UTC bands update the sidebar without adding cards', async ({ page }, testInfo) => {
  await page.getByRole('button', { name: /Peru\. Press Enter to select/ }).click()
  await expect(page.getByText('America / Lima').first()).toBeVisible()
  await expect(page.getByText('Peru').first()).toBeVisible()
  await expect(page.locator('.timezone-card')).toHaveCount(1)
  await expect(page.getByRole('heading', { name: 'Country', exact: true })).toHaveCount(0)

  await page.getByRole('button', { name: 'Select UTC', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Countries at UTC' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Ghana', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Iceland', exact: true })).toBeVisible()
  await expect(page.locator('.selected-country')).toHaveCount(0)
  expect(await page.locator('.related-country').count()).toBeGreaterThan(1)
  await expect(page.getByRole('article')).toHaveCount(1)
  await page.screenshot({ path: testInfo.outputPath('utc-band-countries.png'), fullPage: true })

  await page.getByRole('button', { name: 'Ghana', exact: true }).click()
  await expect(page.getByText('Africa / Abidjan').first()).toBeVisible()
  await expect(page.getByRole('button', { name: /Accra Capital UTC/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Country', exact: true })).toHaveCount(0)
  await expect(page.locator('.selected-country')).toHaveCount(1)
})

test('country drilldown returns to the originating UTC offset list', async ({ page }) => {
  await page.getByRole('button', { name: 'Select UTC+1', exact: true }).click()
  await page.getByRole('button', { name: 'United Kingdom', exact: true }).click()
  const back = page.getByRole('button', { name: 'Back to UTC+1' })
  await expect(back).toBeVisible()
  await back.click()
  await expect(page.getByRole('heading', { name: 'Countries at UTC+1' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'United Kingdom', exact: true })).toBeVisible()
})

test('country label does not block selecting a neighbouring country', async ({ page }) => {
  await page.getByRole('button', { name: /Côte d'Ivoire\. Press Enter to select/ }).click()
  await expect(page.getByText("Côte d'Ivoire").first()).toBeVisible()
  await page.getByRole('button', { name: /Ghana\. Press Enter to select/ }).click()
  await expect(page.getByText('Ghana').first()).toBeVisible()
  await expect(page.getByText('Africa / Abidjan').first()).toBeVisible()
})

test('selecting a timezone card always shows its country label without a map marker', async ({ page }, testInfo) => {
  await page.getByRole('combobox', { name: /search cities/i }).fill('Europe/Warsaw')
  await page.getByRole('option', { name: /Warsaw/i }).first().click()
  await page.getByRole('button', { name: 'Add to comparison' }).click()
  await page.locator('svg.rsm-svg').click({ position: { x: 5, y: 5 } })
  await page.getByRole('article').filter({ hasText: 'Warsaw' }).click()

  const label = page.locator('.active-marker')
  await expect(page.locator('.selected-country')).toHaveCount(1)
  await expect(label.getByText('Poland')).toBeVisible()
  await expect(label.getByText('Warsaw')).toBeVisible()
  await expect(label.locator('.marker-time')).toHaveText(/^\d{1,2}:\d{2} (?:AM|PM)$/)
  await expect(label.locator('circle:not(.marker-dot)')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('location-details.png'), fullPage: true })
})

test('UTC bands stay synchronized with map pan and zoom', async ({ page }, testInfo) => {
  const mapTransform = page.locator('.rsm-zoomable-group')
  const bandTransform = page.locator('.band-transform')
  const synchronized = async () => {
    const mapValue = await mapTransform.getAttribute('transform')
    const bandValue = await bandTransform.getAttribute('transform')
    const mapMatch = mapValue?.match(/translate\(([-\d.]+) [-\d.]+\) scale\(([-\d.]+)\)/)
    const bandMatch = bandValue?.match(/translate\(([-\d.]+) 0\) scale\(([-\d.]+) 1\)/)
    return Boolean(mapMatch && bandMatch && Math.abs(Number(mapMatch[1]) - Number(bandMatch[1])) < 0.01 && Math.abs(Number(mapMatch[2]) - Number(bandMatch[2])) < 0.01)
  }

  await expect.poll(synchronized).toBe(true)
  const initialTransform = await mapTransform.getAttribute('transform')
  const initialBandWidth = (await page.getByRole('button', { name: 'Select UTC', exact: true }).boundingBox())!.width
  await page.getByRole('button', { name: 'Zoom in' }).click()
  await expect.poll(synchronized).toBe(true)
  expect(await mapTransform.getAttribute('transform')).not.toBe(initialTransform)
  expect((await page.getByRole('button', { name: 'Select UTC', exact: true }).boundingBox())!.width).toBeGreaterThan(initialBandWidth)

  const map = page.getByRole('img', { name: /world map/i })
  const bounds = (await map.boundingBox())!
  await page.mouse.move(bounds.x + bounds.width * 0.65, bounds.y + bounds.height * 0.55)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width * 0.45, bounds.y + bounds.height * 0.55, { steps: 5 })
  await page.mouse.up()
  await expect.poll(synchronized).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('panned-zoomed-map.png'), fullPage: true })
})

test('large countries keep a scrollable, searchable timezone list', async ({ page }, testInfo) => {
  await page.getByRole('button', { name: /United States of America\. Press Enter to select/ }).click()
  const sidebar = page.getByRole('complementary', { name: 'Selected timezone details' })
  expect(await sidebar.evaluate((element) => element.scrollHeight > element.clientHeight)).toBe(true)
  const selectedTimezone = sidebar.locator('.timezone-option.selected')
  await expect(selectedTimezone).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await expect(selectedTimezone).toHaveCSS('border-left-color', 'rgb(229, 57, 53)')
  await page.getByRole('textbox', { name: 'Filter timezones' }).fill('PST')
  await expect(page.getByRole('button', { name: /America\/Los Angeles.*PDT.*PST/i })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('filtered-timezones.png'), fullPage: true })
})

test('desktop workspace keeps cards beneath the map and the sidebar at full workspace height', async ({ page }) => {
  test.skip((await page.viewportSize())!.width <= 800, 'Desktop layout assertion')
  await expect(page.getByText('Drag to reorder')).toHaveCount(0)
  await expect(page.getByText(/All times are saved/i)).toHaveCount(0)

  const sidebar = await page.getByRole('complementary', { name: 'Selected timezone details' }).boundingBox()
  const map = await page.locator('.map-panel').boundingBox()
  const card = await page.getByRole('article').first().boundingBox()

  expect(sidebar).not.toBeNull()
  expect(map).not.toBeNull()
  expect(card).not.toBeNull()
  expect(map!.height).toBeGreaterThanOrEqual(500)
  expect(card!.height).toBeLessThanOrEqual(100)
  expect(card!.x).toBeGreaterThanOrEqual(map!.x)
  expect(sidebar!.height).toBeGreaterThanOrEqual(map!.height)
  await expect(page.getByRole('button', { name: 'Add City' })).toHaveCount(0)
  expect(await page.locator('.card-row').evaluate((element) => getComputedStyle(element).gridTemplateColumns.split(' ').length)).toBe(5)
})

test('mobile map prioritizes selected country details and wraps cards after deselection', async ({ page }) => {
  test.skip((await page.viewportSize())!.width > 800, 'Mobile layout assertion')
  const search = page.getByRole('combobox', { name: /search cities/i })
  const timeFormat = page.getByRole('button', { name: /change time format/i })
  const home = page.locator('.home-button')
  const [searchBox, timeFormatBox, homeBox] = await Promise.all([search.boundingBox(), timeFormat.boundingBox(), home.boundingBox()])
  expect(searchBox).not.toBeNull()
  expect(timeFormatBox).not.toBeNull()
  expect(homeBox).not.toBeNull()
  expect(timeFormatBox!.x).toBeGreaterThanOrEqual(searchBox!.x + searchBox!.width)
  expect(homeBox!.x).toBeGreaterThanOrEqual(timeFormatBox!.x + timeFormatBox!.width)
  expect(Math.abs(timeFormatBox!.y - searchBox!.y)).toBeLessThan(2)
  expect(Math.abs(homeBox!.y - searchBox!.y)).toBeLessThan(2)

  const strip = page.getByRole('region', { name: 'Compared timezones' })
  await expect(strip).toBeHidden()

  await page.locator('svg.rsm-svg').click({ position: { x: 5, y: 5 } })
  await expect(strip).toBeVisible()
  await expect(page.locator('.selected-country')).toHaveCount(0)

  await page.getByRole('combobox', { name: /search cities/i }).fill('Asia/Tokyo')
  await page.getByRole('option', { name: /Tokyo/i }).first().click()
  await page.getByRole('button', { name: 'Add to comparison' }).click()
  await page.locator('svg.rsm-svg').click({ position: { x: 5, y: 5 } })
  await page.getByRole('combobox', { name: /search cities/i }).fill('Asia/Kolkata')
  await page.getByRole('option', { name: /Delhi/i }).first().click()
  await page.getByRole('button', { name: 'Add to comparison' }).click()
  await page.locator('svg.rsm-svg').click({ position: { x: 5, y: 5 } })
  const cards = page.locator('.timezone-card')
  const first = (await cards.nth(0).boundingBox())!
  const second = (await cards.nth(1).boundingBox())!
  const third = (await cards.nth(2).boundingBox())!
  expect(Math.abs(second.y - first.y)).toBeLessThan(2)
  expect(second.x).toBeGreaterThan(first.x + first.width)
  expect(third.y).toBeGreaterThan(first.y + first.height)
})

test('renders the responsive comparison experience', async ({ page }, testInfo) => {
  await expect(page.getByText('Current offsets · includes daylight saving')).toBeVisible()
  await expect(page.getByText(/UTC\+1 now/)).toBeVisible()
  const sidebar = page.getByRole('complementary', { name: 'Selected timezone details' })
  await expect(sidebar.locator('.zone-city')).toHaveText('London')
  await expect(sidebar.locator('.zone-country')).toHaveText('United Kingdom')
  await expect(sidebar.getByText('Europe / London', { exact: true })).toBeVisible()
  await expect(page.getByText(/Standard offset:/)).toHaveCount(0)
  await expect(page.getByRole('img', { name: /world map/i })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Compare' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Timezones', exact: true })).toHaveCount(0)
  await page.getByRole('combobox', { name: /search cities/i }).fill('America/New_York')
  await page.getByRole('option', { name: /New York/i }).first().click()
  await page.getByRole('button', { name: 'Add to comparison' }).click()
  await page.getByRole('button', { name: 'Compare' }).click()
  await expect(page.getByRole('heading', { name: 'Compare' })).toBeVisible()
  await expect(page.getByText('Scroll to see the full day')).toHaveCount(0)
  await expect(page.getByText('Maximum overlap')).toHaveCount(0)
  await expect(page.locator('.overlap-row')).toHaveCount(2)
  await expect(page.locator('.overlap-row').first().locator('.hour-cell')).toHaveCount(24)
  const firstHour = page.locator('.hour-cell strong').first()
  await expect(firstHour).toHaveCSS('font-size', '13px')
  await expect(firstHour).toHaveText(/^12$/)
  await expect(page.locator('.hour-cell small').first()).toHaveText(/^AM$/)
  await expect(page.locator('.hour-cell small').first()).toHaveCSS('font-size', '7px')
  await page.getByRole('button', { name: /change time format/i }).click()
  await expect(firstHour).toHaveCSS('font-size', '13px')
  await expect(firstHour).toHaveText(/^00$/)
  await expect(page.locator('.hour-cell small')).toHaveCount(0)
  await page.getByRole('button', { name: /change time format/i }).click()
  await expect(page.getByText('Home', { exact: true })).toHaveCount(0)
  await expect(page.locator('.overlap-location').first().getByLabel('Home timezone')).toBeAttached()
  await expect(page.locator('.overlap-location').first().locator('span')).toHaveCSS('font-size', '22px')
  await expect(page.locator('.overlap-location').first().locator('span')).toHaveCSS('font-weight', '500')
  await expect(page.locator('.overlap-location').first().locator('span')).not.toContainText('·')
  await expect(page.locator('.overlap-row').first().locator('.hour-cell em')).toHaveCount(0)
  const offsetRow = page.locator('.overlap-row').nth(1)
  expect(await offsetRow.locator('.hour-cell em').count()).toBeGreaterThan(1)
  const differentDayCell = offsetRow.locator('.hour-cell:has(em)').first()
  const [dayBox, timeBox] = await Promise.all([differentDayCell.locator('em').boundingBox(), differentDayCell.locator('strong').boundingBox()])
  expect(dayBox!.y).toBeLessThan(timeBox!.y)
  await expect(page.locator('.current-time').first()).toHaveCSS('background-color', 'rgb(229, 57, 53)')
  await expect(page.locator('.current-time').getByText('Now', { exact: true })).toHaveCount(1)
  if ((await page.viewportSize())!.width <= 800) {
    const settingsToggle = page.getByRole('button', { name: 'Show schedule settings' })
    await expect(settingsToggle).toHaveAttribute('aria-expanded', 'false')
    await expect(page.getByLabel('Working hours start')).toBeHidden()
    await settingsToggle.click()
    await expect(page.getByRole('button', { name: 'Hide schedule settings' })).toHaveAttribute('aria-expanded', 'true')
    const chart = page.locator('.overlap-chart')
    const marker = page.locator('.current-time').first()
    const location = page.locator('.overlap-fixed-location').first()
    await expect.poll(async () => {
      const [chartBox, markerBox, locationBox] = await Promise.all([chart.boundingBox(), marker.boundingBox(), location.boundingBox()])
      if (!chartBox || !markerBox || !locationBox) return Number.POSITIVE_INFINITY
      const cellAreaCenter = locationBox.x + locationBox.width + (chartBox.width - locationBox.width) / 2
      return Math.abs(markerBox.x - cellAreaCenter)
    }).toBeLessThan(20)
    expect(await location.evaluate((element) => getComputedStyle(element).backgroundColor)).not.toBe('rgba(0, 0, 0, 0)')
  } else {
    await expect(page.locator('.schedule-settings-toggle')).toBeHidden()
  }
  await expect(page.getByLabel('Working hours start')).toHaveValue('9')
  await expect(page.getByLabel('Nighttime start')).toHaveValue('22')
  await page.getByLabel('Nighttime start').selectOption('21')
  await page.reload()
  await page.getByRole('button', { name: 'Compare' }).click()
  if ((await page.viewportSize())!.width <= 800) {
    await page.getByRole('button', { name: 'Show schedule settings' }).click()
  }
  await expect(page.getByLabel('Nighttime start')).toHaveValue('21')
  await expect(page.locator('.hour-cell.work:not(.current-hour)').first()).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(page.locator('.hour-cell.work:not(.current-hour)').first()).toHaveCSS('color', 'rgb(0, 0, 0)')
  await expect(page.locator('.hour-cell.other:not(.current-hour)').first()).toHaveCSS('background-color', 'rgb(191, 191, 191)')
  await expect(page.locator('.hour-cell.other:not(.current-hour)').first()).toHaveCSS('color', 'rgb(0, 0, 0)')
  await expect(page.locator('.hour-cell.night:not(.current-hour)').first()).toHaveCSS('background-color', 'rgb(0, 0, 0)')
  await expect(page.locator('.hour-cell.night:not(.current-hour)').first()).toHaveCSS('color', 'rgb(255, 255, 255)')
  await expect(page.locator('.hour-cell.current-hour').first()).toHaveCSS('color', 'rgb(229, 57, 53)')
  await expect(page.locator('.current-time > span')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await page.screenshot({ path: testInfo.outputPath('world-time.png'), fullPage: true })

  await page.evaluate(() => { document.documentElement.dataset.theme = 'dark' })
  await expect(page.locator('.hour-cell.work:not(.current-hour)').first()).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(page.locator('.hour-cell.work:not(.current-hour)').first()).toHaveCSS('color', 'rgb(0, 0, 0)')
  await expect(page.locator('.hour-cell.other:not(.current-hour)').first()).toHaveCSS('background-color', 'rgb(191, 191, 191)')
  await expect(page.locator('.hour-cell.other:not(.current-hour)').first()).toHaveCSS('color', 'rgb(0, 0, 0)')
  await expect(page.locator('.hour-cell.night:not(.current-hour)').first()).toHaveCSS('background-color', 'rgb(0, 0, 0)')
  await expect(page.locator('.hour-cell.night:not(.current-hour)').first()).toHaveCSS('color', 'rgb(255, 255, 255)')
  await expect(page.locator('.hour-cell.current-hour').first()).toHaveCSS('color', 'rgb(255, 81, 77)')
  await page.screenshot({ path: testInfo.outputPath('world-time-dark.png'), fullPage: true })
})
